### ISSUE TITLE
Issue: Multiple SolanaClients mix responses with each other

### ISSUE THREAD

**Issue by Virus-Axel** [Virus-Axel/godot-solana-sdk#180]
### Description

When using multiple clients simultaneously they get each others responses.

### Suggested Improvements

Make use of IDs in requests and listen only to responses with that ID.

### Extra Information

This is an acceptable solution for now but is inefficient and should be reworked later.

**Comment by cre8andctrl** [comment]
Hey there. Just started looking into the SDK and I'm looking to integrate nfts into the project. Hope this works. Cheers!

**Comment by Virus-Axel** [comment]
Hi, @cre8andctrl! Yes NFTs are supported. If you would like some support on making it work we can keep the conversation on discord.

**Comment by cre8andctrl** [comment]
> Hi, @cre8andctrl! Yes NFTs are supported. If you would like some support on making it work we can keep the conversation on discord.

Hello, @Virus-Axel ! Yeah that would be awesome. Do you have a channel that I can join?

**Comment by Virus-Axel** [comment]
Yes, maybe this one https://discord.gg/WvwDeZtZ
