### ISSUE TITLE
Metadata Fetching freezes on certain images

### ISSUE THREAD

**Issue by ZenRepublic** [Virus-Axel/godot-solana-sdk#188]
### Description

Usually, and error is throw immediately, but with certain nfts (mostly scam ones) fetching metadata stops the entire process for a very long time before error is returned

this one for example:
https://ipfs.io/ipfs/bafkreihpa6rnq2bcog7lmxtzx2wzaiaaxu2o7ardfwmyhuepnht3ctjn6y

### Suggested Improvements

maybe add a 5 second timeout or something?

**Comment by Virus-Axel** [comment]
Timeout property added to SolanaClient. MetadataNode can now access SolanaClient properties.
