### ISSUE TITLE
Please add a functionality to deserialize a transaction

### ISSUE THREAD

**Issue by ZenRepublic** [Virus-Axel/godot-solana-sdk#197]
### Description

Would be cool to turn a serialized transaction from byte array into Transaction class.
Usecase being receiving a constructed transaction from elsewhere and only have a user pay for it.

Something like "Transaction.new_from_bytes(byte_array)" would be nice

**Comment by Virus-Axel** [comment]
Transaction.new_from_bytes(byte_array) merged to master
