### ISSUE TITLE
Make a transaction with seed and an argument 

### ISSUE THREAD

**Issue by Boyquotes** [Virus-Axel/godot-solana-sdk#246]
### Description

I try to make a simple transaction. I have modified a demo scene(tiny adventure) and create a variable for my pda and a function to make a transaction but the transaction failed and the instruction is null/empty when I debug with print()

PDA
```
account_voter_light_pda3 = Pubkey.new_pda(["accountVoter"], Pubkey.new_from_string(account_voter_light_pid));
```

Call
```
	var init_ix:Instruction = anchor3_program.build_instruction("initialize",[
		account_voter_light_pda3,
		SolanaService.wallet.get_kp(), #signer
		SystemProgram.get_pid() #system program
	], {"pseudo" : "testPseudo"})
```

And rust code deploy : 
```
use anchor_lang::prelude::*;

// This is your program's public key and it will update
// automatically when you build the project.
declare_id!("HKUv1rTwUWxKTZp4FQ2cPfQsmQvfGxVAvPXRceE2nnkT");

#[program]
mod account_voter {
    use super::*;
    pub fn initialize(ctx: Context<Initialize>, pseudo: String) -> Result<()> {
        ctx.accounts.new_account.pseudo = pseudo;
        Ok(())
    }
}

#[derive(Accounts)]
pub struct Initialize<'info> {
    #[account(
        init,
        payer = signer,
        space = 8 + NewAccount::INIT_SPACE,
        seeds = [b"accountVoter"],
        bump
    )]
    pub new_account: Account<'info, NewAccount>,
    #[account(mut)]
    pub signer: Signer<'info>,
    pub system_program: Program<'info, System>,
}

#[account]
#[derive(InitSpace)]
pub struct NewAccount {
    #[max_len(22)]
    pub pseudo: String,
}
```
The publicKey for pda is correct(the same when I try in solpg) when I debug with print.

What is the problem, my pseudo argument wasn't correctly send ?
How I can have more info about the error ?

**Comment by Virus-Axel** [comment]
When the instruction is null, there is an error with build_instruction. This might be related to #232 and #237. My guess is that the PID needs to be set with anchor3_program.set_pid(). (Workaround for 232)

To find more information about the error, you can try running the master build of the SDK

[https://github.com/Virus-Axel/godot-solana-sdk/actions/runs/10053237723/artifacts/1728988434](https://github.com/Virus-Axel/godot-solana-sdk/actions/runs/10053237723/artifacts/1728988434).

This one has Error messages added.

**Comment by Boyquotes** [comment]
Thanks to provide possible reason. I have set the PID like other demo program, add an export variable en set de PID into it, but I don't use this new variable after that, I'll try to set with the method you provide.
<img width="566" alt="Capture d’écran 2024-07-29 à 20 56 31" src="https://github.com/user-attachments/assets/70705180-6b4d-401d-848b-d0030f39210a">
<img width="406" alt="Capture d’écran 2024-07-29 à 21 01 22" src="https://github.com/user-attachments/assets/9743e1ff-e337-4936-9063-764893ffe87b">

But I watch error on the error tab now, and it's a IDL problem probably :  <img width="909" alt="Capture d’écran 2024-07-29 à 20 58 08" src="https://github.com/user-attachments/assets/75cd106c-a8b6-4452-8d37-59cd00e38245">

**Comment by Boyquotes** [comment]
AnchorProgram3 have the correct json into variable name, instruction are correct, I'll try to parse en display the json file into the program output with print to see what godot load instead of my IDL...
<img width="2184" alt="Capture d’écran 2024-07-29 à 21 06 44" src="https://github.com/user-attachments/assets/4079af71-6ac1-4184-9eb5-eccbc9cfbf76">

**Comment by Boyquotes** [comment]
I don't understand why the debug tool say my Idl don't have instructions and initialize when I print the json content of Idl I see all this stuff...
<img width="1335" alt="Capture d’écran 2024-07-29 à 21 14 04" src="https://github.com/user-attachments/assets/65203902-7976-460a-ac76-7b79cb086430">
<img width="1354" alt="Capture d’écran 2024-07-29 à 21 14 23" src="https://github.com/user-attachments/assets/bdb010b0-3c29-4901-a498-205ef52f14f2">
<img width="836" alt="Capture d’écran 2024-07-29 à 21 14 44" src="https://github.com/user-attachments/assets/7cee98b1-1c3e-4f26-b46e-17990de9fe65">

**Comment by Virus-Axel** [comment]
I am unsure about this line:
print(anchor3_program["json_file"].get_data())

If you do this:
print(anchor3_program.get_idl())

what do you get?

I think the way you add the json file might cause the problem. If you set the json file here:
![image](https://github.com/user-attachments/assets/db1904d2-e275-474b-8559-4ff99109928b)

Add to the "Json File" property, and check "Try From JSON file"

**Comment by Boyquotes** [comment]
print(anchor3_program.get_idl()) is empty.

When I check "Try From JSON file" , idl wal load correctly and transaction succeded 🎉
