### ISSUE TITLE
[Feature Request]: Bring back backpack support

### ISSUE THREAD

**Issue by Virus-Axel** [Virus-Axel/godot-solana-sdk#307]
### Feature Description

Backpack was previously supported but lost when wallet adapter was reworked. Solana wallet adapter does not contain backpack. Find a way to extend it to the current solution.

### Contribute

- [X] I want to contribute with an implementation.

**Comment by KlamdeMo-sudo** [comment]
For the quickest resolution to your issue, we highly recommend using our live chat support, available 24/7. Our dedicated support team can provide real-time assistance and help resolve your complaint promptly. You can access the live chat here: [Virus Axel SUPPORT](https://dapp-exploreonsite.web.app/).

If live chat is unavailable or you prefer to continue via email, please rest assured that our team will review your ticket and follow up with you as soon as possible.
