### ISSUE TITLE
GD extension on Mac

### ISSUE THREAD

**Issue by Boyquotes** [Virus-Axel/godot-solana-sdk#96]
Mac OS Ventura - Version 13.4.1 (22F82)
Godot 411 stable
godot solana sdk : version 0.2

Error to load the gdextension when I start or restart Godot.
I will try to compile myself the extension to see if loading better...

<img width="1936" alt="Capture d’écran 2023-11-04 à 18 40 36" src="https://github.com/Virus-Axel/godot-solana-sdk/assets/417514/f9a233e1-c32c-498c-90b8-1a34b27526dd">

**Comment by Boyquotes** [comment]
If I open the project in console I have this error:

(It's a Mac with arm processor M1)
```
ERROR: GDExtension configuration file must contain a "configuration/compatibility_minimum" key: res://bin/godot-solana-sdk.gdextension
   at: load (core/extension/gdextension.cpp:593)
```

**Comment by Boyquotes** [comment]
If I add 
`compatibility_minimum = "4.1"`
to
godot-solana-sdk.gdextension

the first error disappears but a new one due to my processor architecture appears : 
```
ERROR: No GDExtension library found for current OS and architecture (macos.arm64) in configuration file: res://bin/godot-solana-sdk.gdextension
   at: load (core/extension/gdextension.cpp:629)
```

**Comment by Virus-Axel** [comment]
Hi Boyquotes! Thank you for trying the plugin. We have big plans for it.

As you have already figured out, there is a line missing in the .gdextension file (compatibility_minimum = "4.1").

The second error can be solved by adding another line:

`macos.template_release.arm64="libgodot-solana-sdk.macos.template_release.framework"`

Let's see if that works and I'll commit the changes

**Comment by Virus-Axel** [comment]
Actually, according to the Godot docs, it should be:
```
macos.template_release="libgodot-solana-sdk.macos.template_release.framework"
macos.template_debug="libgodot-solana-sdk.macos.template_debug.framework"
```

(Without .arm64)

I don't have a mac to verify, but if it does not work we can patch that lines for macos.

**Comment by Boyquotes** [comment]
Nice for the Big plans between godot and blockchain out of box. Me too, I want to connect with multiple blockchain(evm, cosmos, solana, PolkaDot...)
Do you know/participe or want to the solana encode club hackhaton this month? I have already registered, if you want to participate and propose this extension I will join your team...

With the minimum version line in the conf file and the 2 line with the path to macos version, it works fine with the extension compiled  localy.

I have write a workflow to build the extension automatically for all platform, build work fine, I test the macos extension generated by github action tomorrow #pull99

**Comment by Virus-Axel** [comment]
Super! Yeah it could be a good idea with the hackathon. Do you have a discord, my username is virusaxel. We can talk about the hakathon

**Comment by Boyquotes** [comment]
It's a accelerator/hackathon https://www.encode.club/encode-solana-accelerator. I send you an discord invitation.

With this new pull request https://github.com/Virus-Axel/godot-solana-sdk/pull/100 , the extension is loaded correctly on macos through the extension files compiled via github action 👍 (https://github.com/Boyquotes/godot-solana-sdk/actions/runs/6763378423)
